name: planificador_bodas
description: "Aplicación para planificación de bodas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'  # Ajustado para ser compatible con tu versión

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.6

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Descomenta y usa estas secciones cuando necesites agregar assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700